name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
            distribution: 'zulu'
            java-version: 8

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-

      - name: Build
        run: mvn --batch-mode dependency:go-offline

      - name: Test
        run: mvn -e --batch-mode test

      - name: JUnit Report
        uses: depsypher/junit-report-annotations-action@master
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          slack-channel-id: C49T7Q53R
